AWSTemplateFormatVersion: '2010-09-09'
Description: Nested Stack
Parameters:
  NodeVersion:
    Type: String
    Default: nodejs10.x
    Description: Version of NodeJS to use.
  LambdaRoleName:
    Type: String
    Default: lambda-role
    Description: Version of NodeJS to use.
Resources:
  Nested1:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/cf-deploy-nested-stack/37156a1a9a4d422fd865ba1d80e88c97/ab3198c2a26f0c7eeb478339fd8527df.template
  Nested2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/cf-deploy-nested-stack/37156a1a9a4d422fd865ba1d80e88c97/19608ec66b7d5495f6fc6be4c780b39c.template
