AWSTemplateFormatVersion: "2010-09-09"
Description: Nested Stack
Parameters:
  NodeVersion:
    Type: String
    Default: "nodejs10.x"
    Description: Version of NodeJS to use.
  LambdaRoleName:
    Type: String
    Default: "lambda-role"
    Description: Version of NodeJS to use.
Resources:
  Nested1:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: stack/nested1/cloudformation.packaged.yaml

  Nested2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: stack/nested2/cloudformation.packaged.yaml
